TrailsClient/Models/TrailMarker.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel;

namespace TrailsClient.Models
{
  public class TrailMarker
  {
    public int TrailMarkerId { get; set; }

    public virtual Trail Trail { get; set; }

    [DisplayName("Choose Trail")]
    public int TrailId { get; set; }

    public string Name { get; set; }

    public double Longitude { get; set; }

    public double Latitude { get; set; }

    [DisplayName("Trailhead")]
    public bool isTrailhead { get; set; }

    [DisplayName("Landmark")]
    public bool isLandmark { get; set; }

    public string Description { get; set; }

    public static List<TrailMarker> GetTrailMarkers()
    {
      var apiCallTask = ApiHelper.GetAll();
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<TrailMarker> TrailMarkerList = JsonConvert.DeserializeObject<List<TrailMarker>>(jsonResponse.ToString());

      return TrailMarkerList;
    }

    //key differences between GetTrailMarkers() and GetDetails(): 1. GetDetails The method will return a singular TrailMarker. 2. GetDetails() will take an id. 3. the API call results in a JSOn object as opposed to a JSON array
    public static TrailMarker GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get(id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      TrailMarker TrailMarker = JsonConvert.DeserializeObject<TrailMarker>(jsonResponse.ToString());

      return TrailMarker;
    }

    public static void Post(TrailMarker TrailMarker)
    {
      string jsonTrailMarker = JsonConvert.SerializeObject(TrailMarker);//converts TrailMarker object into JSON 
      var apiCallTask = ApiHelper.Post(jsonTrailMarker);
    }

    public static void Put(TrailMarker TrailMarker)
    {
      string jsonTrailMarker = JsonConvert.SerializeObject(TrailMarker);
      var apiCallTask = ApiHelper.Put(TrailMarker.TrailMarkerId, jsonTrailMarker);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete(id);
    }
  }
}

TrailsClient/Controllers/TrailMarkersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TrailsClient.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TrailsClient.Controllers
{
  public class TrailMarkersController : Controller
  {
    private readonly ILogger<TrailMarkersController> _logger;

    public TrailMarkersController(ILogger<TrailMarkersController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      var allTrailMarkers = TrailMarker.GetTrailMarkers();
      return View(allTrailMarkers);
    }

    public IActionResult Details(int id)
    {
      var thisTrailMarker = TrailMarker.GetDetails(id);

      return View(thisTrailMarker);
    }

    public IActionResult Create()
    {
      ViewBag.TrailId = new SelectList (Trail.GetTrails(), "TrailId", "Name");
      return View();
    }

    [HttpPost]
    public IActionResult Create(TrailMarker trailMarker)
    {
      var thisTrail = Trail.GetDetails(trailMarker.TrailId);
      thisTrail.TrailMarkers.Add(trailMarker);
      TrailMarker.Post(trailMarker);
      return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
      var thisTrailMarker = TrailMarker.GetDetails(id);
      return View(thisTrailMarker);
    }

    [HttpPost]
    public IActionResult Edit(TrailMarker trailMarker)
    {
      TrailMarker.Put(trailMarker);
      return RedirectToAction("Details", new { id = trailMarker.TrailMarkerId });
    }

    public IActionResult Delete(int id)
      {
        var thisTrailMarker = TrailMarker.GetDetails(id);
        return View(thisTrailMarker);
      }

      [HttpPost, ActionName("Delete")]
      public IActionResult DeleteConfirmed(int id)
      {
        TrailMarker.Delete(id);
        return RedirectToAction("Index");
      }
  }
} 

TrailsClient/Views/TrailMarkers/Create.cshtml
@{
  Layout = "_LayoutP";
}

@model TrailsClient.Models.TrailMarker

<div class="container" id="createView">
  <div class="row" >
    <div class = "col-md-4 text-center no-float" id="createTrailMarkerForm">
      <h1>Add a new Trail Marker</h1>
        @using (Html.BeginForm())
        {
          <div class="settings">
            @Html.HiddenFor(model => model.TrailMarkerId)

            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name)
            
            @Html.LabelFor(model => model.Longitude)
            @Html.EditorFor(model => model.Longitude)

            @Html.LabelFor(model => model.Latitude)
            @Html.EditorFor(model => model.Latitude)  

            @Html.LabelFor(model => model.isLandmark)
            @Html.EditorFor(model => model.isLandmark)

            @Html.LabelFor(model => model.isTrailhead)
            @Html.EditorFor(model => model.isTrailhead)

            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description)

            @Html.LabelFor(model => model.TrailId)
            @Html.DisplayFor(model => model.TrailId)
            @Html.DropDownList("TrailId", null, "-----------", new {@class="form-control"})
          </div>

          <input class = "btn btn-secondary" type="submit" value="Add Trail Marker"/>
        }
    </div>
    <div class = "col-md-8 no-float">
      <div id="viewDiv"></div>
    </div>
  </div>
</div>  

@section Scripts
{
<style>
  #viewDiv {
    padding: 0;
    margin: 0;
    height: 100vh;
    width: 100vw;
  }
</style>
  <link rel="stylesheet" href="https://js.arcgis.com/4.24/esri/themes/light/main.css">
  <script src="https://js.arcgis.com/4.24/"></script>
  <script>

require([
  "esri/config",
  "esri/Map",
  "esri/views/MapView",

  "esri/rest/locator"

], function(esriConfig,Map, MapView, locator) {

  esriConfig.apiKey = "AAPK7691fadea68d4c688c09d108d1cd1d7cSxgmrGZq1iMecdeWEN29tO3QCLIzXUFXyg4PLvxYtshTAFhyxYK6D4d2m-vnNbrK";

  const map = new Map({
    basemap: "arcgis-topographic"
  });

  const view = new MapView({
    container: "viewDiv",
    map: map,
    center: [-122.62495,45.52118],
    zoom: 12
  });

  //display selected trail map
   @await Html.PartialAsync("_displaySelectedTrail", new { id = )
          let model = @Html.Raw(Json.Serialize(Model));//convert C# model to Javascript object
        console.log(model);
        let trailMarkersCoordinates = [];
        for ( let i = 0; i < model.trailMarkers.length; i++){
          trailMarkersCoordinates.push([model.trailMarkers[i].longitude, model.trailMarkers[i].latitude]);
        }
        
        const polyline = {
        type: "polyline",
        paths: trailMarkersCoordinates
          };
          const simpleLineSymbol = {
            type: "simple-line",
            color: [226, 119, 40], // Orange
            width: 2
          };
          const polylineGraphic = new Graphic({
          geometry: polyline,
          symbol: simpleLineSymbol
          });
          graphicsLayer.add(polylineGraphic);
  //end of selected trail map

  const serviceUrl = "http://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer";

  view.on("click", function(evt){
      const params = {
        location: evt.mapPoint
      };

      locator.locationToAddress(serviceUrl, params)
        .then(function(response) { // Show the address found
          const address = response.address;
          showAddress(address, evt.mapPoint);
        }, function(err) { // Show no address found
          showAddress("No address found.", evt.mapPoint);
        });

        var long = Math.round(evt.mapPoint.longitude * 100000)/100000;
        var lat = Math.round(evt.mapPoint.latitude * 100000)/100000;

        document.getElementsByName('Longitude')[0].value = long;
        document.getElementsByName('Latitude')[0].value = lat;
    });

  function showAddress(address, pt) {
    view.popup.open({
      title:  + Math.round(pt.longitude * 100000)/100000 + ", " + Math.round(pt.latitude * 100000)/100000,
      content: address,
      location: pt,

    });
  }

});
</script>

}

TrailsClient/Views/TrailMarkers/Details.cshtml
@{
  Layout = "_LayoutP";
}

@model TrailsClient.Models.TrailMarker

<div class="container">
  <div class="row" id="trailMarkerDetails">
    <div class="col-md-4 trailMarkDeetz card overflow-auto">
        <h1>Trailmarker Info:</h1>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">ID: @Model.TrailMarkerId</li>
            <li class="list-group-item">Name: @Model.Name</li>
            <li class="list-group-item">Longitude: @Model.Longitude</li>
            <li class="list-group-item">Latitude: @Model.Latitude</li>
            <li class="list-group-item">Trailhead?: @Model.isTrailhead</li>
            <li class="list-group-item">Landmark?: @Model.isLandmark</li>
            <li class="list-group-item">Description: @Model.Description</li>
        </ul>

        <div class="d-flex justify-content-center">
          <a href="/Home/Index"><button id="homeTMIButton"></button></a>
        </div>
      </div>
      <div class="col-md-8" id="viewDiv"></div>
  </div>
</div>

  @section Scripts
  {
  
    <style>
        html,
        body,
        #viewDiv {
          padding: 0;
            margin: 0;
            height: 100vh;
            width: 100vw;
        }
      </style>
      
    <link rel="stylesheet" href="https://js.arcgis.com/4.24/esri/themes/light/main.css">
    <script src="https://js.arcgis.com/4.24/"></script>

    <script>
      require(["esri/config","esri/Map", "esri/views/MapView", "esri/Graphic", "esri/layers/GraphicsLayer"], function (esriConfig, Map, MapView, Graphic, GraphicsLayer) {

        esriConfig.apiKey = "AAPK7691fadea68d4c688c09d108d1cd1d7cSxgmrGZq1iMecdeWEN29tO3QCLIzXUFXyg4PLvxYtshTAFhyxYK6D4d2m-vnNbrK";

        const map = new Map({
          basemap: "arcgis-topographic" // Basemap layer service
        });

        const view = new MapView({
          map: map,
          center: [@Model.Longitude, @Model.Latitude], // Longitude, latitude
          zoom: 16, // Zoom level
          container: "viewDiv" // Div element
        });

        const graphicsLayer = new GraphicsLayer();
        map.add(graphicsLayer);

        //add point at coordinates
        const point = { //Create a point
        type: "point",
        longitude: @Model.Longitude,
        latitude: @Model.Latitude
        };
        
        //style point marker
        const simpleMarkerSymbol = {
          type: "simple-marker",
          color: [36, 122, 151],  //blue
          outline: {
            color: [255, 255, 255], // White
            width: 1
          }
        };
        const pointGraphic = new Graphic({
          geometry: point,
          symbol: simpleMarkerSymbol
        });
          graphicsLayer.add(pointGraphic);
        });
        </script>
  }

TrailsClient/Views/TrailMarkers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TrailsClient.Models.TrailMarker

<h1>Edit this trail marker: @Html.DisplayFor(model => model.Name)</h1>

@using (Html.BeginForm())
{
  <div class="settings">
  @Html.HiddenFor(model => model.TrailMarkerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Longitude)
  @Html.EditorFor(model => model.Longitude)

  @Html.LabelFor(model => model.Latitude)
  @Html.EditorFor(model => model.Latitude)  

  @Html.LabelFor(model => model.isLandmark)
  @Html.EditorFor(model => model.isLandmark)

  @Html.LabelFor(model => model.isTrailhead)
  @Html.EditorFor(model => model.isTrailhead)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  <input class="btn btn-secondary" type="submit" value="Save" />
  </div>
}

<hr
<a href="/TrailMarkers/Details/@(Model.TrailMarkerId)"><p>Return to Details</p></a>

TrailsClient/Views/TrailMarkers/Index.cshtml
@{
  Layout = "_LayoutP";

  }

<div class="container d-flex" id="trailMarkerIndexView">
  <div class="row">
    <div class="col-md-4 trailMarkersList">
      <div class="nav justify-content-end" style="padding-top: 10px;">
        <p class="btn btn-info">@Html.ActionLink("Create Trail Marker", "Create")</p>
      </div>
      <div class="">
      <h2>All TrailMarkers:</h2>
      </div>

      <div class="card overflow-auto">
        <ul class="list-group list-group-flush">
          @foreach (TrailMarker trailMarker in Model)
          {
            <p class="list-group-item">@Html.ActionLink($"{trailMarker.Name}", "Details", "TrailMarkers", new {id =
            trailMarker.TrailMarkerId})</p>
          }
        </ul>
      </div>
      <div class="d-flex justify-content-center">
          <a href="/Home/Index"><button id="homeTMIButton"></button></a>
      </div>
    </div>
    <div class="col-md-8">
      <div id="viewDiv"></div>
    </div>
  </div>
</div>

@section Scripts
{
<style>
  @* html,
  body, *@
  #viewDiv {
    padding: 0;
    margin: 0;
    height: 100vh;
    width: 100vw;
  }
</style>

<link rel="stylesheet" href="https://js.arcgis.com/4.24/esri/themes/light/main.css">
<script src="https://js.arcgis.com/4.24/"></script>

<script>
  require(["esri/config", "esri/Map", "esri/views/MapView", "esri/Graphic", "esri/layers/GraphicsLayer"], function (esriConfig, Map, MapView, Graphic, GraphicsLayer) {

    esriConfig.apiKey = "AAPK7691fadea68d4c688c09d108d1cd1d7cSxgmrGZq1iMecdeWEN29tO3QCLIzXUFXyg4PLvxYtshTAFhyxYK6D4d2m-vnNbrK";

    const map = new Map({
      basemap: "arcgis-topographic" // Basemap layer service
    });

    const view = new MapView({
      map: map,
      center: [-122.62495, 45.52118], // Longitude, latitude --Laurelhurst Park OR
      zoom: 10, // Zoom level
      container: "viewDiv" // Div element
    });

    const graphicsLayer = new GraphicsLayer();
    map.add(graphicsLayer);

    let model = @Html.Raw(Json.Serialize(Model));//convert C# model to Javascript object

    for (let i = 0; i < model.length; i++) {
      const point = { //Create a point
        type: "point",
        longitude: model[i]['longitude'],
        latitude: model[i]['latitude']
        //longitude: -122.62495,
        //latitude: 45.52118
      };

      //style point marker
      const simpleMarkerSymbol = {
        type: "simple-marker",
        color: [36, 122, 151], // button blue
        outline: {
          color: [255, 255, 255], // White
          width: 1
        }
      };

      const popupTemplate = {
        title: "{Name}",
        content: "{Description}"
      }
      const attributes = {
        Name: model[i]['name'],
        Description: model[i]['description']
      }
      const pointGraphic = new Graphic({
        geometry: point,
        symbol: simpleMarkerSymbol,

        attributes: attributes,
        popupTemplate: popupTemplate
      });
      graphicsLayer.add(pointGraphic);
    }
  });
</script>
}